Repository l3vels/l3-ui-core, pull requests merged in 2023-03, with the labels that each got.

#55 fix: update modal component
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalHelper.ts
  src/components/Modal/__stories__/Modal.stories.scss
  src/components/Modal/__stories__/helpers.js
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/modal-snapshot-tests.jest.js
  src/components/ModalHeader/ModalHeader.module.scss
Labels: PR: New Feature 🕹

#61 Update package.json
  package.json
Labels: PR: Dependencies 🛠

#62 fix: updated avatar component
  src/components/Avatar/Avatar.scss
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/AvatarConstants.tsx
  src/components/Avatar/__stories__/assets/azuki_1.jpg
  src/components/Avatar/__stories__/assets/azuki_2.jpg
  src/components/Avatar/__stories__/assets/azuki_3.jpg
  src/components/Avatar/__stories__/assets/azuki_4.jpg
  src/components/Avatar/__stories__/assets/bird_1.jpg
  src/components/Avatar/__stories__/assets/bird_2.jpg
  src/components/Avatar/__stories__/assets/bird_3.jpg
  src/components/Avatar/__stories__/assets/bird_4.jpg
  src/components/Avatar/__stories__/assets/bird_5.jpg
  src/components/Avatar/__stories__/assets/bird_6.jpg
  src/components/Avatar/__stories__/assets/clone_1.jpg
  src/components/Avatar/__stories__/assets/clone_10.jpg
  src/components/Avatar/__stories__/assets/clone_11.jpg
  src/components/Avatar/__stories__/assets/clone_2.jpg
  src/components/Avatar/__stories__/assets/clone_3.jpg
  src/components/Avatar/__stories__/assets/clone_4.jpg
  src/components/Avatar/__stories__/assets/clone_5.jpg
  src/components/Avatar/__stories__/assets/clone_6.jpg
  src/components/Avatar/__stories__/assets/clone_7.jpg
  src/components/Avatar/__stories__/assets/clone_8.jpg
  src/components/Avatar/__stories__/assets/clone_9.jpg
  src/components/Avatar/__stories__/assets/index.js
  src/components/Avatar/__stories__/assets/monkey_1.jpg
  src/components/Avatar/__stories__/assets/monkey_2.jpg
  src/components/Avatar/__stories__/assets/monkey_3.jpg
  src/components/Avatar/__stories__/assets/monkey_4.jpg
  src/components/Avatar/__stories__/assets/monkey_5.jpg
  src/components/Avatar/__stories__/assets/monkey_6.jpg
  src/components/Avatar/__stories__/assets/punk1.jpg
  src/components/Avatar/__stories__/assets/punk2.jpg
  src/components/Avatar/__stories__/assets/punk4.jpg
  src/components/Avatar/__stories__/assets/punk5.jpg
  src/components/Avatar/__stories__/assets/punk6.jpg
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.scss
  src/components/Avatar/avatar.stories.helperComponents.tsx
  src/components/Icon/__stories__/Icon.stories.mdx
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
Labels: PR: New Feature 🕹

#63 Fix/update main issues
  package-lock.json
  src/components/Avatar/Avatar.scss
  src/components/Avatar/avatar.stories.helperComponents.tsx
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Tooltip/Tooltip.scss
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipConstants.ts
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
Labels: PR: Dependencies 🛠

#64 Update package.json
  package.json
Labels: PR: Dependencies 🛠

#60 Fix/divider
  src/components/Divider/Divider.scss
  src/components/Divider/Divider.tsx
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/Divider/__stories__/Divider.stories.module.scss
  src/components/Divider/__tests__/divider.jest.tsx
  src/components/Menu/MenuDivider/MenuDivider.tsx
  src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#66 Fix/toast build
  package-lock.json
  package.json
  src/components/Icon/Icons/components/Alert.tsx
  src/components/Icon/Icons/components/CloseGray.tsx
  src/components/Icon/Icons/components/CloseWhite.tsx
  src/components/Icon/Icons/components/NegativeCheck.tsx
  src/components/Icon/Icons/components/PositiveCheck.tsx
  src/components/Icon/Icons/components/SpeaciaWarningInfo.tsx
  src/components/Icon/Icons/components/SpeacialCheck.tsx
  src/components/Icon/Icons/components/SpecialWarning.tsx
  src/components/Icon/Icons/components/Vector.tsx
  src/components/Icon/Icons/components/WarningCheck.tsx
  src/components/Icon/Icons/index.ts
  src/components/Toast/ToastConstants.ts
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: Breaking Changes 💥

#68 Fix/update search v1
  package-lock.json
  package.json
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Search/Search.tsx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/TextField.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#69 fix: update text field
  package-lock.json
  package.json
  src/components/TextField/TextField.tsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: Breaking Changes 💥

#71 fix: updated toast component
  src/components/Toast/Toast.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastConstants.ts
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: Breaking Changes 💥

#72 Fix/tags component
  package.json
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Tags/Tags.module.scss
  src/components/Tags/Tags.tsx
  src/components/Tags/__stories__/tags.stories.mdx
  src/components/Tags/__tests__/__snapshots__/tags-snapshot-tests.jest.tsx.snap
  src/styles/theme-mixin.scss
  src/utils/colors-vars-map.ts
Labels: PR: Bugfix 🐛

#76 Update package.json
  package.json
Labels: PR: Bugfix 🐛

#78 fix: tags & dropdown
  package.json
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/DropdownIndicator/DropdownIndicator.jsx
  src/components/Tags/Tags.module.scss
  src/components/Tags/Tags.tsx
  src/components/Tags/__tests__/__snapshots__/tags-snapshot-tests.jest.tsx.snap
Labels: PR: Bugfix 🐛

#75 fix: updated badge component
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/Badge/BadgeConstants.ts
  src/components/Badge/__stories__/badge.stories.mdx
  src/components/Badge/__stories__/badge.stories.scss
  src/components/Icon/Icons/components/Games.tsx
Labels: PR: New Feature 🕹

#79 fix: wizard
  package.json
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
Labels: PR: Bugfix 🐛

#80 fix: wizard stepNumber
  package.json
  src/components/MultiStepIndicator/MultiStepIndicator.jsx
Labels: PR: Bugfix 🐛

#81 fix: updated modal size
  package-lock.json
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#83 fix: updated modal component
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/__stories__/Modal.stories.scss
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/ModalContent/ModalContent.module.scss
  src/components/ModalFooter/ModalFooter.module.scss
  src/components/ModalHeader/ModalHeader.module.scss
  src/components/ModalHeader/ModalHeader.tsx
  src/components/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#82 Update package.json
  package.json
Labels: PR: Dependencies 🛠

#86 fix: textare
  package.json
  src/components/Textarea/Textarea.module.scss
  src/components/Textarea/Textarea.tsx
  src/components/Textarea/__stories__/Textarea.stories.mdx
Labels: PR: Bugfix 🐛

#85 fix: updated modal components
  src/components/Modal/Modal.module.scss
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/ModalContent/ModalContent.module.scss
  src/components/ModalHeader/ModalHeader.module.scss
  src/components/ModalHeader/ModalHeader.tsx
  src/components/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Toast/Toast.scss
  src/components/Toast/ToastConstants.ts
  src/components/Toast/__stories__/toast.stories.mdx
Labels: PR: New Feature 🕹
