Repository l3vels/l3-ui-core, pull requests merged in 2023-02, with the labels that each got.

#16 Fix/typography label
  src/components/IconButton/IconButton.module.scss
  src/styles/typography/display-typography.scss
  src/styles/typography/main-typography.scss
  src/styles/typography/typography.scss
Labels: PR: Dependencies 🛠

#17 Fix/edit dropdown
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/dropdown-constants.js
Labels: PR: Breaking Changes 💥

#21 fix: I replaced the span with a typographer's label.
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/IconButton/IconButton.module.scss
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/Tags/__tests__/__snapshots__/tags-snapshot-tests.jest.tsx.snap
Labels: PR: Icon 💎

#22 fix: update colros
  .storybook/preview-head.html
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/storybook/components/color-description/color-description.jsx
  src/storybook/components/colors-description/colors-description.jsx
  src/storybook/components/content-colors-main/content-colors-main.jsx
  src/storybook/components/frame/frams.scss
  src/storybook/components/text-colors/text-colors.jsx
  src/storybook/stand-alone-documentaion/colors/background-colors/background-colors.jsx
  src/storybook/stand-alone-documentaion/colors/border-colors/border-colors.jsx
  src/storybook/stand-alone-documentaion/colors/colors.stories.mdx
  src/storybook/stand-alone-documentaion/colors/colors.stories.module.scss
  src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
Labels: PR: Breaking Changes 💥

#23 Fix/date picker styles
  src/components/DatePicker/DateNavigationItem/DateNavigationItem.module.scss
  src/components/DatePicker/DatePicker.module.scss
  src/components/DatePicker/DatePickerHeader/DatePickerHeader.module.scss
  src/components/DatePicker/YearPicker/YearPicker.module.scss
  src/components/DatePicker/YearPicker/YearPicker.tsx
  src/components/DatePicker/YearPicker/YearsList.tsx
  src/styles/theme-mixin.scss
Labels: PR: Bugfix 🐛

#24 fix: primary colors
  src/styles/theme-mixin.scss
  src/styles/typography/main-typography.scss
Labels: PR: Breaking Changes 💥

#27 fix: typography
  src/storybook/stand-alone-documentaion/typography/Typography.tsx
  src/storybook/stand-alone-documentaion/typography/TypographyConstants.tsx
  src/storybook/stand-alone-documentaion/typography/typography.scss
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
  src/styles/typography/display-typography.scss
  src/styles/typography/main-typography.scss
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#25 Feat/textarea
  src/components/Textarea/Textarea.module.scss
  src/components/Textarea/Textarea.tsx
  src/components/Textarea/__stories__/Textarea.stories.mdx
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#28 Fix/editable heading
  src/components/EditableHeading/EditableHeading.scss
  src/components/EditableInput/EditableInput.scss
  src/components/Heading/Heading.scss
Labels: PR: Bugfix 🐛

#29 Update package.json
  package.json
Labels: PR: Breaking Changes 💥

#31 Fix/update style export
  src/components/Toggle/Toggle.tsx
  src/components/index.js
Labels: PR: Breaking Changes 💥

#32 update version of package.json
  package.json
Labels: PR: Bugfix 🐛

#30 Fix/menu
  src/components/Avatar/Avatar.scss
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/__stories__/assets/Polygon 18-10.png
  src/components/Avatar/__stories__/assets/Polygon 18-11.png
  src/components/Avatar/__stories__/assets/Polygon 18-12.png
  src/components/Avatar/__stories__/assets/Polygon 18-5.png
  src/components/Avatar/__stories__/assets/Polygon 18-6.png
  src/components/Avatar/__stories__/assets/Polygon 18-7.png
  src/components/Avatar/__stories__/assets/Polygon 18-8.png
  src/components/Avatar/__stories__/assets/Polygon 18-9.png
  src/components/Avatar/__stories__/assets/Polygon 18.png
  src/components/Avatar/__stories__/assets/avatar1.png
  src/components/Avatar/__stories__/assets/avatar2.png
  src/components/Avatar/__stories__/assets/avatar3.png
  src/components/Avatar/__stories__/assets/avatar4.png
  src/components/Avatar/__stories__/assets/index.js
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/DialogContentContainer/DialogContentContainer.scss
  src/components/Menu/Menu/__stories__/Menu.stories.module.scss
  src/components/Menu/Menu/__stories__/menu.stories.js
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuItem/MenuItem.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/Menu/MenuTitle/MenuTitle.scss
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/Menu/MenuTitle/MenuTitleConstants.ts
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
Labels: PR: New Feature 🕹

#33 Update package.json
  package.json
Labels: PR: Breaking Changes 💥

#34 Fix/update menu v2
  package.json
  src/components/DialogContentContainer/DialogContentContainer.scss
  src/components/Menu/Menu/Menu.scss
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__stories__/menu.stories.js
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuItem/MenuItem.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuTitle/MenuTitle.scss
  src/components/Menu/MenuTitle/MenuTitle.tsx
Labels: PR: Breaking Changes 💥

#35 feat: card component
  package-lock.json
  src/components/Card/Card.scss
  src/components/Card/Card.tsx
  src/components/Card/__stories__/assets/defaultImg.png
  src/components/Card/__stories__/assets/mainImg.png
  src/components/Card/__stories__/card.stories.mdx
  src/components/Heading/Heading.tsx
  src/components/Heading/HeadingConstants.ts
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#36 feat: badge dots
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/Badge/BadgeConstants.ts
  src/components/Badge/__stories__/badge.stories.mdx
  src/styles/theme-mixin.scss
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#37 fix: updaate storybook fonts
  .gitignore
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/preview.js
  fonts/circular-medium/circular-std-medium.eot
  fonts/circular-medium/circular-std-medium.ttf
  fonts/circular-medium/circular-std-medium.woff
  fonts/circular-medium/circular-std-medium.woff2
  fonts/circular-medium/stylesheet.css
  fonts/circular-normal/CircularStd-Book.eot
  fonts/circular-normal/CircularStd-Book.ttf
  fonts/circular-normal/CircularStd-Book.woff
  fonts/circular-normal/CircularStd-Book.woff2
  fonts/circular-normal/stylesheet.css
  package-lock.json
  package.json
  src/styles/typography/main-typography.scss
Labels: PR: Breaking Changes 💥

#39 fix: menuTitle component
  src/components/Heading/Heading.scss
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuTitle/MenuTitle.scss
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.mdx
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
Labels: PR: Bugfix 🐛

#41 fix: update iconts
  package.json
  src/components/Icon/Icons/components/API.tsx
  src/components/Icon/Icons/components/About.tsx
  src/components/Icon/Icons/components/ArrowLeft.tsx
  src/components/Icon/Icons/components/ArrowRight.tsx
  src/components/Icon/Icons/components/BulletList.tsx
  src/components/Icon/Icons/components/Players.tsx
  src/components/Icon/Icons/index.ts
  src/components/Menu/MenuItem/MenuItem.tsx
Labels: PR: Breaking Changes 💥

#44 Update package.json
  package.json
Labels: PR: Breaking Changes 💥

#46 fix: editableHeading autofocus & menuTitle props children
  package.json
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableInput/EditableInput.tsx
  src/components/EditableInput/__tests__/__snapshots__/editableInput.jest.js.snap
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.mdx
Labels: PR: Bugfix 🐛

#47 Fix/update bugs v2
  package.json
  src/components/Icon/Icons/components/ArrowDownOutline.tsx
  src/components/Icon/Icons/components/ArrowLeftOutline.tsx
  src/components/Icon/Icons/components/ArrowRightOutline.tsx
  src/components/Icon/Icons/components/ArrowUpOutline.tsx
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuItem/MenuItem.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
Labels: PR: Breaking Changes 💥

#49 Update package.json
  package.json
Labels: PR: Icon 💎

#50 Fix/storybook exports
  package-lock.json
  package.json
  src/components/index.js
Labels: PR: Dependencies 🛠

#52 Fix/avatar sizes
  src/components/Avatar/Avatar.scss
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuTitle/MenuTitle.scss
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
Labels: PR: Bugfix 🐛

#53 fix: update version
  package.json
Labels: PR: Bugfix 🐛

#54 Fix/tab size
  package-lock.json
  package.json
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/Tab/__stories__/tab.stories.mdx
  src/components/Tabs/TabList/__stories__/tab-list.stories.mdx
  src/components/Tabs/TabPanel/__stories__/tab-panel.stories.mdx
  src/components/Tabs/TabPanels/__stories__/tab-panels.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.mdx
Labels: PR: Bugfix 🐛

#57 fix: tablist size
  package-lock.json
  package.json
  src/components/Tabs/TabList/TabList.scss
Labels: PR: Bugfix 🐛

#58 Fix/update bugs v1
  .storybook/fonts/circular-medium/circular-std-medium.eot
  .storybook/fonts/circular-medium/circular-std-medium.ttf
  .storybook/fonts/circular-medium/circular-std-medium.woff
  .storybook/fonts/circular-medium/circular-std-medium.woff2
  .storybook/fonts/circular-medium/stylesheet.css
  .storybook/fonts/circular-normal/CircularStd-Book.eot
  .storybook/fonts/circular-normal/CircularStd-Book.ttf
  .storybook/fonts/circular-normal/CircularStd-Book.woff
  .storybook/fonts/circular-normal/CircularStd-Book.woff2
  .storybook/fonts/circular-normal/stylesheet.css
  src/components/Dialog/Dialog.scss
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogContent/DialogContent.scss
  src/components/Dialog/arrow-svg.tsx
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Tooltip/Tooltip.scss
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
  src/controls/Type=top.svg
  src/fonts/circular-medium/circular-std-medium.eot
  src/fonts/circular-medium/circular-std-medium.ttf
  src/fonts/circular-medium/circular-std-medium.woff
  src/fonts/circular-medium/circular-std-medium.woff2
  src/fonts/circular-medium/stylesheet.css
  src/fonts/circular-normal/CircularStd-Book.eot
  src/fonts/circular-normal/CircularStd-Book.ttf
  src/fonts/circular-normal/CircularStd-Book.woff
  src/fonts/circular-normal/CircularStd-Book.woff2
  src/fonts/circular-normal/stylesheet.css
Labels: PR: Bugfix 🐛

#59 fix: remove heading padding
  package.json
  src/components/Heading/Heading.scss
Labels: PR: Bugfix 🐛

#56 fix: update alertBanner
  src/components/AlertBanner/AlertBanner.scss
  src/components/AlertBanner/AlertBanner.tsx
  src/components/AlertBanner/AlertBannerConstants.ts
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#45 Fix/alert banner
  package-lock.json
  package.json
  src/components/Avatar/__stories__/assets/person6.png
  src/components/Icon/Icons/components/Alert.tsx
  src/components/Icon/Icons/components/CloseGray.tsx
  src/components/Icon/Icons/components/CloseWhite.tsx
  src/components/Icon/Icons/components/NegativeCheck.tsx
  src/components/Icon/Icons/components/PositiveCheck.tsx
  src/components/Icon/Icons/components/Vector.tsx
  src/components/Icon/Icons/components/WarningCheck.tsx
  src/components/Icon/Icons/index.ts
  src/components/Toast/Toast.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastArtWork/ToastArtWork.tsx
  src/components/Toast/ToastConstants.ts
  src/components/Toast/ToastHelpers.tsx
  src/components/Toast/__stories__/assets/Polygon 18-10.png
  src/components/Toast/__stories__/assets/Polygon 18-11.png
  src/components/Toast/__stories__/assets/Polygon 18-12.png
  src/components/Toast/__stories__/assets/Polygon 18-5.png
  src/components/Toast/__stories__/assets/Polygon 18-6.png
  src/components/Toast/__stories__/assets/Polygon 18-7.png
  src/components/Toast/__stories__/assets/Polygon 18-8.png
  src/components/Toast/__stories__/assets/Polygon 18-9.png
  src/components/Toast/__stories__/assets/Polygon 18.png
  src/components/Toast/__stories__/assets/avatar1.png
  src/components/Toast/__stories__/assets/avatar2.png
  src/components/Toast/__stories__/assets/avatar3.png
  src/components/Toast/__stories__/assets/avatar4.png
  src/components/Toast/__stories__/assets/femaleIcon.png
  src/components/Toast/__stories__/assets/guest.svg
  src/components/Toast/__stories__/assets/home.svg
  src/components/Toast/__stories__/assets/index.js
  src/components/Toast/__stories__/assets/maleIcon.png
  src/components/Toast/__stories__/assets/minus.svg
  src/components/Toast/__stories__/assets/owner.svg
  src/components/Toast/__stories__/assets/person1.png
  src/components/Toast/__stories__/assets/person2.png
  src/components/Toast/__stories__/assets/person3.png
  src/components/Toast/__stories__/assets/person4.png
  src/components/Toast/__stories__/assets/person5.png
  src/components/Toast/__stories__/assets/person6.png
  src/components/Toast/__stories__/assets/person7.png
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toast/__stories__/toast.stories.scss
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/styles/theme-mixin.scss
Labels: PR: New Feature 🕹
