Repository l3vels/l3-ui-core, pull requests merged in 2023-01, with the labels that each got.

#4 Feat/typography
  src/components/TextField/TextField.scss
  src/styles/display-typography.scss
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
Labels: PR: Bugfix 🐛

#5 fix: bem prefix
  src/components/Slider/SliderConstants.ts
  src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
Labels: PR: Breaking Changes 💥

#7 Fix/update main components
  src/components/Button/Button.scss
  src/components/TextField/TextField.scss
  src/styles/global-css-settings.scss
Labels: PR: Breaking Changes 💥

#2 Fix/styles
  src/components/Checkbox/Checkbox.jsx
  src/components/Checkbox/Checkbox.scss
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.js.snap
  src/components/RadioButton/RadioButton.scss
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButton/RadioButtonConstants.ts
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/RadioButton/__tests__/__snapshots__/radioButton-snapshot-tests.jest.tsx.snap
  src/components/Toggle/Toggle.scss
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
Labels: PR: Bugfix 🐛

#9 Fix/button group
  src/components/ButtonGroup/ButtonGroup.scss
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/__stories__/buttonGroup.stories.mdx
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.tsx.snap
  src/components/ButtonGroup/__tests__/buttonGroup-snapshot-tests.jest.tsx
Labels: PR: Bugfix 🐛

#8 Fix/loader
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Loader/Loader.module.scss
  src/components/Loader/Loader.tsx
  src/components/Loader/LoaderConstants.ts
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
  src/components/Loader/__tests__/loader-snapshots.jest.js
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__tests__/__snapshots__/linearProgressBar-snapshot-tests.jest.js.snap
  src/components/ProgressBars/LinearProgressBar/__tests__/linearProgressBar-tests.jest.js
  src/components/ProgressBars/PercentageLabel/PercentageLabel.jsx
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/Tab/Tab.tsx
  src/components/Tabs/Tab/TabConstants.ts
  src/components/Tabs/Tab/__stories__/tab.stories.mdx
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/TabList.scss
  src/components/Tabs/TabList/TabList.tsx
  src/components/Tabs/TabList/__stories__/tab-list.stories.mdx
  src/components/Tabs/TabList/__stories__/tab-list.stories.module.scss
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
Labels: PR: Bugfix 🐛

#11 Fix/date picker
  src/components/DatePicker/DateNavigationItem/DateNavigationItem.module.scss
  src/components/DatePicker/DateNavigationItem/DateNavigationItem.tsx
  src/components/DatePicker/DatePicker.module.scss
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/DatePickerHeader/DatePickerHeader.module.scss
  src/components/DatePicker/__stories__/datepicker.stories.mdx
  src/components/DatePicker/constants.ts
  src/components/Icon/Icons/components/MoveArrowLeft.tsx
  src/components/Icon/Icons/components/MoveArrowRight.tsx
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
Labels: PR: Bugfix 🐛

#12 Fix/search componnet update
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Search/Search.tsx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/TextField.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: Breaking Changes 💥

#10 fix: add square button in icon button component
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/IconButton/IconButton.module.scss
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#13 Fix/tags
  src/components/Button/__stories__/button.stories.mdx
  src/components/Chips/Chips.module.scss
  src/components/Chips/ChipsConstants.ts
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__stories__/dropdown.stories.scss
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/driver.js
  src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
  src/components/Dropdown/__tests__/dropdown-tests.jest.js
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
  src/components/Dropdown/dropdown-constants.js
  src/components/Dropdown/hooks/useHiddenOptionsData.js
  src/components/Flex/__stories__/Flex.stories.mdx
  src/components/Flex/__stories__/Flex.stories.module.scss
  src/components/Label/__stories__/label.stories.mdx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Tags/Tags.module.scss
  src/components/Tags/Tags.tsx
  src/components/Tags/TagsConstants.ts
  src/components/Tags/__stories__/assets/person1.png
  src/components/Tags/__stories__/tags.stories.mdx
  src/components/Tags/__stories__/tags.stories.scss
  src/components/Tags/__tests__/__snapshots__/tags-snapshot-tests.jest.tsx.snap
  src/components/Tags/__tests__/tags-snapshot-tests.jest.tsx
  src/components/Tags/__tests__/tags-tests.jest.tsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/index.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/tags-description.jsx
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
  src/tests/constants.ts
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#15 Fix/update verstion
  package-lock.json
  src/components/DatePicker/DateNavigationItem/DateNavigationItem.module.scss
  src/components/DatePicker/DatePickerHeader/DatePickerHeader.module.scss
  src/components/Icon/Icons/components/MoveArrowLeft.tsx
  src/components/Icon/Icons/components/MoveArrowRight.tsx
Labels: PR: Breaking Changes 💥
